// Career paths with their required skills
export const CAREER_PATHS = [
  {
    title: "Full Stack Web Developer",
    category: "Technology",
    description: "Builds end-to-end web applications covering both frontend and backend development.",
    avgSalaryMin: 35000,
    avgSalaryMax: 90000,
    demandLevel: "VERY_HIGH",
    requirements: [
      { skill: "HTML", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "CSS", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "JavaScript", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "React", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Node.js", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "REST APIs", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "SQL", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Git", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "TypeScript", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Next.js", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Docker", importance: "RECOMMENDED", minLevel: "BEGINNER" },
      { skill: "PostgreSQL", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Tailwind CSS", importance: "OPTIONAL", minLevel: "INTERMEDIATE" },
    ],
  },
  {
    title: "Frontend Developer",
    category: "Technology",
    description: "Specializes in building user interfaces and client-side web applications.",
    avgSalaryMin: 30000,
    avgSalaryMax: 75000,
    demandLevel: "VERY_HIGH",
    requirements: [
      { skill: "HTML", importance: "REQUIRED", minLevel: "EXPERT" },
      { skill: "CSS", importance: "REQUIRED", minLevel: "EXPERT" },
      { skill: "JavaScript", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "React", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "TypeScript", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Git", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "REST APIs", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Responsive Design", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Next.js", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Tailwind CSS", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Testing", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
    ],
  },
  {
    title: "Backend Developer",
    category: "Technology",
    description: "Builds server-side logic, APIs, and database systems.",
    avgSalaryMin: 32000,
    avgSalaryMax: 80000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "Node.js", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "REST APIs", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "SQL", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "PostgreSQL", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Git", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "JavaScript", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "TypeScript", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Docker", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Authentication & Security", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Cloud Deployment", importance: "OPTIONAL", minLevel: "BEGINNER" },
    ],
  },
  {
    title: "Data Analyst",
    category: "Data & Analytics",
    description: "Analyzes data to generate business insights and support decision-making.",
    avgSalaryMin: 28000,
    avgSalaryMax: 65000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "Python", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "SQL", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Excel", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Data Visualization", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Statistics", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Power BI", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Pandas", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Tableau", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Machine Learning Basics", importance: "OPTIONAL", minLevel: "BEGINNER" },
    ],
  },
  {
    title: "Data Scientist",
    category: "Data & Analytics",
    description: "Uses statistical and machine learning methods to extract insights from large datasets.",
    avgSalaryMin: 40000,
    avgSalaryMax: 100000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "Python", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Machine Learning", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Statistics", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "SQL", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Pandas", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "NumPy", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Data Visualization", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Deep Learning", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "TensorFlow", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Cloud Platforms", importance: "OPTIONAL", minLevel: "BEGINNER" },
    ],
  },
  {
    title: "DevOps Engineer",
    category: "Technology",
    description: "Automates and streamlines software delivery and infrastructure management.",
    avgSalaryMin: 38000,
    avgSalaryMax: 95000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "Docker", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Kubernetes", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Linux", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "CI/CD Pipelines", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Cloud Platforms", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Git", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Shell Scripting", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Terraform", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Monitoring & Observability", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
    ],
  },
  {
    title: "UI/UX Designer",
    category: "Design",
    description: "Designs intuitive user interfaces and experiences for digital products.",
    avgSalaryMin: 25000,
    avgSalaryMax: 70000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "Figma", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "User Research", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Wireframing", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Prototyping", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Design Systems", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Usability Testing", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Typography", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "HTML", importance: "RECOMMENDED", minLevel: "BEGINNER" },
      { skill: "CSS", importance: "RECOMMENDED", minLevel: "BEGINNER" },
    ],
  },
  {
    title: "Mobile App Developer",
    category: "Technology",
    description: "Builds mobile applications for iOS and Android platforms.",
    avgSalaryMin: 30000,
    avgSalaryMax: 80000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "React Native", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "JavaScript", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "TypeScript", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "REST APIs", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Git", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "App Deployment", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "State Management", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Testing", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
    ],
  },
  {
    title: "Cybersecurity Analyst",
    category: "Technology",
    description: "Protects systems and networks from digital attacks and security breaches.",
    avgSalaryMin: 35000,
    avgSalaryMax: 90000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "Network Security", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Linux", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Security Auditing", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Penetration Testing", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Cryptography", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Python", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "SIEM Tools", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Cloud Security", importance: "OPTIONAL", minLevel: "BEGINNER" },
    ],
  },
  {
    title: "Digital Marketing Specialist",
    category: "Marketing",
    description: "Manages online marketing campaigns, SEO, and digital brand strategy.",
    avgSalaryMin: 20000,
    avgSalaryMax: 55000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "SEO", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Social Media Marketing", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Google Analytics", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Content Marketing", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Email Marketing", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "PPC Advertising", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Copywriting", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Canva", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
    ],
  },
  {
    title: "Product Manager",
    category: "Product & Management",
    description: "Leads product strategy, roadmap, and cross-functional team coordination.",
    avgSalaryMin: 40000,
    avgSalaryMax: 110000,
    demandLevel: "HIGH",
    requirements: [
      { skill: "Product Strategy", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Agile/Scrum", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "User Research", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Data Analysis", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Communication", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Stakeholder Management", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "SQL", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
      { skill: "Figma", importance: "RECOMMENDED", minLevel: "BEGINNER" },
    ],
  },
  {
    title: "Cloud Engineer",
    category: "Technology",
    description: "Designs, builds, and manages cloud infrastructure and services.",
    avgSalaryMin: 40000,
    avgSalaryMax: 100000,
    demandLevel: "VERY_HIGH",
    requirements: [
      { skill: "Cloud Platforms", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "AWS", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Docker", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Kubernetes", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Linux", importance: "REQUIRED", minLevel: "ADVANCED" },
      { skill: "Infrastructure as Code", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Networking", importance: "REQUIRED", minLevel: "INTERMEDIATE" },
      { skill: "Security Best Practices", importance: "RECOMMENDED", minLevel: "INTERMEDIATE" },
    ],
  },
];

export const SKILLS_TAXONOMY = [
  // Programming Languages
  { name: "JavaScript", category: "Programming Languages", description: "Dynamic scripting language for web development" },
  { name: "TypeScript", category: "Programming Languages", description: "Typed superset of JavaScript" },
  { name: "Python", category: "Programming Languages", description: "Versatile language for data science, AI, and web" },
  { name: "Java", category: "Programming Languages", description: "Object-oriented language for enterprise applications" },
  { name: "C++", category: "Programming Languages", description: "High-performance systems programming language" },
  { name: "Go", category: "Programming Languages", description: "Efficient language for scalable backend services" },
  { name: "Rust", category: "Programming Languages", description: "Systems language focused on memory safety" },
  { name: "PHP", category: "Programming Languages", description: "Server-side scripting language for web" },
  { name: "Ruby", category: "Programming Languages", description: "Dynamic language optimized for developer productivity" },
  { name: "Swift", category: "Programming Languages", description: "Language for iOS and macOS development" },
  { name: "Kotlin", category: "Programming Languages", description: "Modern JVM language for Android development" },

  // Frontend
  { name: "HTML", category: "Frontend Development", description: "Markup language for structuring web content" },
  { name: "CSS", category: "Frontend Development", description: "Stylesheet language for web presentation" },
  { name: "React", category: "Frontend Development", description: "UI library for building component-based interfaces" },
  { name: "Next.js", category: "Frontend Development", description: "React framework with SSR and routing" },
  { name: "Vue.js", category: "Frontend Development", description: "Progressive JavaScript framework" },
  { name: "Angular", category: "Frontend Development", description: "TypeScript-based SPA framework" },
  { name: "Tailwind CSS", category: "Frontend Development", description: "Utility-first CSS framework" },
  { name: "Responsive Design", category: "Frontend Development", description: "Designing adaptive web layouts for all screens" },
  { name: "State Management", category: "Frontend Development", description: "Managing application state in frontend apps" },
  { name: "Testing", category: "Frontend Development", description: "Writing and running automated tests" },

  // Backend
  { name: "Node.js", category: "Backend Development", description: "JavaScript runtime for server-side development" },
  { name: "Express.js", category: "Backend Development", description: "Minimal Node.js web application framework" },
  { name: "REST APIs", category: "Backend Development", description: "Designing and consuming RESTful web services" },
  { name: "GraphQL", category: "Backend Development", description: "Query language and runtime for APIs" },
  { name: "Authentication & Security", category: "Backend Development", description: "Implementing auth systems and securing APIs" },
  { name: "Microservices", category: "Backend Development", description: "Designing distributed service architectures" },

  // Mobile
  { name: "React Native", category: "Mobile Development", description: "Cross-platform mobile app framework using React" },
  { name: "Flutter", category: "Mobile Development", description: "Google UI toolkit for multi-platform apps" },
  { name: "iOS Development", category: "Mobile Development", description: "Building native iPhone/iPad applications" },
  { name: "Android Development", category: "Mobile Development", description: "Building native Android applications" },
  { name: "App Deployment", category: "Mobile Development", description: "Publishing apps to App Store and Play Store" },

  // Databases
  { name: "SQL", category: "Databases", description: "Structured query language for relational databases" },
  { name: "PostgreSQL", category: "Databases", description: "Advanced open-source relational database" },
  { name: "MySQL", category: "Databases", description: "Popular open-source relational database" },
  { name: "MongoDB", category: "Databases", description: "NoSQL document-oriented database" },
  { name: "Redis", category: "Databases", description: "In-memory data structure store" },
  { name: "Database Design", category: "Databases", description: "Designing efficient database schemas" },

  // Cloud & DevOps
  { name: "AWS", category: "Cloud & DevOps", description: "Amazon Web Services cloud platform" },
  { name: "Cloud Platforms", category: "Cloud & DevOps", description: "General cloud computing services (AWS/GCP/Azure)" },
  { name: "Docker", category: "Cloud & DevOps", description: "Containerization platform for applications" },
  { name: "Kubernetes", category: "Cloud & DevOps", description: "Container orchestration platform" },
  { name: "CI/CD Pipelines", category: "Cloud & DevOps", description: "Automating software build and deployment" },
  { name: "Infrastructure as Code", category: "Cloud & DevOps", description: "Managing infrastructure using code" },
  { name: "Terraform", category: "Cloud & DevOps", description: "Infrastructure as code tool for cloud" },
  { name: "Cloud Deployment", category: "Cloud & DevOps", description: "Deploying applications to cloud environments" },
  { name: "Monitoring & Observability", category: "Cloud & DevOps", description: "System monitoring and performance tracking" },

  // Systems & Networking
  { name: "Linux", category: "Systems & Networking", description: "Unix-like operating system administration" },
  { name: "Shell Scripting", category: "Systems & Networking", description: "Writing automation scripts in Bash/Shell" },
  { name: "Networking", category: "Systems & Networking", description: "Computer network fundamentals and protocols" },
  { name: "Network Security", category: "Systems & Networking", description: "Protecting network infrastructure" },

  // AI & ML
  { name: "Machine Learning", category: "AI & Machine Learning", description: "Building systems that learn from data" },
  { name: "Deep Learning", category: "AI & Machine Learning", description: "Neural network based learning systems" },
  { name: "TensorFlow", category: "AI & Machine Learning", description: "Open-source ML framework by Google" },
  { name: "PyTorch", category: "AI & Machine Learning", description: "Dynamic neural network framework" },
  { name: "Natural Language Processing", category: "AI & Machine Learning", description: "Processing and understanding human language" },
  { name: "Computer Vision", category: "AI & Machine Learning", description: "Teaching machines to interpret images" },
  { name: "Machine Learning Basics", category: "AI & Machine Learning", description: "Foundational ML concepts and algorithms" },

  // Data Science
  { name: "Pandas", category: "Data Science", description: "Python library for data manipulation and analysis" },
  { name: "NumPy", category: "Data Science", description: "Numerical computing library for Python" },
  { name: "Statistics", category: "Data Science", description: "Statistical methods for data analysis" },
  { name: "Data Visualization", category: "Data Science", description: "Creating charts and visual representations of data" },
  { name: "Excel", category: "Data Science", description: "Spreadsheet software for data analysis" },
  { name: "Power BI", category: "Data Science", description: "Microsoft business intelligence platform" },
  { name: "Tableau", category: "Data Science", description: "Data visualization software" },
  { name: "Data Analysis", category: "Data Science", description: "Analyzing and interpreting data to extract insights" },

  // Security
  { name: "Cybersecurity", category: "Security", description: "Protecting digital systems from cyber threats" },
  { name: "Penetration Testing", category: "Security", description: "Ethical hacking to find security vulnerabilities" },
  { name: "Security Auditing", category: "Security", description: "Evaluating system security policies and controls" },
  { name: "Cryptography", category: "Security", description: "Encryption and data protection techniques" },
  { name: "SIEM Tools", category: "Security", description: "Security information and event management" },
  { name: "Cloud Security", category: "Security", description: "Security practices for cloud environments" },
  { name: "Security Best Practices", category: "Security", description: "Standard security implementations and coding practices" },

  // Design
  { name: "Figma", category: "Design", description: "Collaborative interface design tool" },
  { name: "User Research", category: "Design", description: "Methods for understanding user needs and behavior" },
  { name: "Wireframing", category: "Design", description: "Creating low-fidelity UI blueprints" },
  { name: "Prototyping", category: "Design", description: "Building interactive design mockups" },
  { name: "Design Systems", category: "Design", description: "Creating reusable component libraries" },
  { name: "Usability Testing", category: "Design", description: "Testing products with real users" },
  { name: "Typography", category: "Design", description: "The art and technique of type arrangement" },
  { name: "Canva", category: "Design", description: "Graphic design tool for non-designers" },

  // Business & Management
  { name: "Product Strategy", category: "Product & Management", description: "Defining product vision and roadmap" },
  { name: "Agile/Scrum", category: "Product & Management", description: "Iterative software development methodology" },
  { name: "Project Management", category: "Product & Management", description: "Planning and executing projects effectively" },
  { name: "Stakeholder Management", category: "Product & Management", description: "Managing relationships with project stakeholders" },

  // Marketing
  { name: "SEO", category: "Marketing", description: "Search engine optimization for organic visibility" },
  { name: "Social Media Marketing", category: "Marketing", description: "Building brand presence on social platforms" },
  { name: "Google Analytics", category: "Marketing", description: "Web analytics service for tracking site performance" },
  { name: "Content Marketing", category: "Marketing", description: "Creating valuable content to attract audience" },
  { name: "Email Marketing", category: "Marketing", description: "Direct marketing through email campaigns" },
  { name: "PPC Advertising", category: "Marketing", description: "Pay-per-click digital advertising campaigns" },
  { name: "Copywriting", category: "Marketing", description: "Writing persuasive marketing content" },

  // Soft Skills
  { name: "Communication", category: "Soft Skills", description: "Effective verbal and written communication" },
  { name: "Problem Solving", category: "Soft Skills", description: "Analytical thinking and creative solution finding" },
  { name: "Leadership", category: "Soft Skills", description: "Guiding and motivating teams toward goals" },
  { name: "Teamwork", category: "Soft Skills", description: "Collaborating effectively with others" },
  { name: "Time Management", category: "Soft Skills", description: "Prioritizing tasks and meeting deadlines" },

  // Tools
  { name: "Git", category: "Tools & Workflow", description: "Version control system for code" },
  { name: "GitHub", category: "Tools & Workflow", description: "Code hosting platform using Git" },
  { name: "Postman", category: "Tools & Workflow", description: "API development and testing tool" },
  { name: "VS Code", category: "Tools & Workflow", description: "Lightweight code editor by Microsoft" },
];

export const SKILL_RELATIONSHIPS = [
  // JavaScript ecosystem
  { skill: "JavaScript", relatedSkill: "TypeScript", type: "LEADS_TO" },
  { skill: "JavaScript", relatedSkill: "React", type: "LEADS_TO" },
  { skill: "JavaScript", relatedSkill: "Node.js", type: "LEADS_TO" },
  { skill: "JavaScript", relatedSkill: "Next.js", type: "LEADS_TO" },
  { skill: "React", relatedSkill: "Next.js", type: "LEADS_TO" },
  { skill: "Node.js", relatedSkill: "Express.js", type: "LEADS_TO" },
  { skill: "TypeScript", relatedSkill: "React", type: "COMPLEMENTARY" },

  // Python ecosystem
  { skill: "Python", relatedSkill: "Pandas", type: "LEADS_TO" },
  { skill: "Python", relatedSkill: "NumPy", type: "LEADS_TO" },
  { skill: "Python", relatedSkill: "Machine Learning", type: "LEADS_TO" },
  { skill: "Pandas", relatedSkill: "NumPy", type: "PREREQUISITE" },
  { skill: "Machine Learning", relatedSkill: "Deep Learning", type: "LEADS_TO" },
  { skill: "Deep Learning", relatedSkill: "TensorFlow", type: "COMPLEMENTARY" },

  // Data path
  { skill: "SQL", relatedSkill: "PostgreSQL", type: "LEADS_TO" },
  { skill: "SQL", relatedSkill: "MySQL", type: "LEADS_TO" },
  { skill: "Statistics", relatedSkill: "Machine Learning", type: "PREREQUISITE" },
  { skill: "Data Analysis", relatedSkill: "Data Visualization", type: "COMPLEMENTARY" },

  // Cloud/DevOps
  { skill: "Docker", relatedSkill: "Kubernetes", type: "LEADS_TO" },
  { skill: "Linux", relatedSkill: "Shell Scripting", type: "LEADS_TO" },
  { skill: "Cloud Platforms", relatedSkill: "AWS", type: "COMPLEMENTARY" },
  { skill: "Git", relatedSkill: "CI/CD Pipelines", type: "LEADS_TO" },

  // Design
  { skill: "Wireframing", relatedSkill: "Prototyping", type: "LEADS_TO" },
  { skill: "User Research", relatedSkill: "Usability Testing", type: "COMPLEMENTARY" },
  { skill: "Figma", relatedSkill: "Design Systems", type: "LEADS_TO" },

  // Mobile
  { skill: "React", relatedSkill: "React Native", type: "LEADS_TO" },
  { skill: "JavaScript", relatedSkill: "React Native", type: "PREREQUISITE" },
];
