// Fallback question bank — used when Gemini AI generation fails

export interface FallbackQuestion {
  question: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: "A" | "B" | "C" | "D";
  explanation: string;
  topic: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
}

export const QUESTION_BANK: Record<string, FallbackQuestion[]> = {
  "Software Developer": [
    {
      question: "What does SOLID stand for in software engineering?",
      optionA: "Single responsibility, Open-closed, Liskov substitution, Interface segregation, Dependency inversion",
      optionB: "Single loop, Object design, Layer interface, Data integration, Design pattern",
      optionC: "Structured, Object, Linked, Independent, Distributed",
      optionD: "Service-oriented, Layered, Interface, Design, Integration",
      correctAnswer: "A",
      explanation: "SOLID is an acronym for five design principles: Single responsibility, Open-closed, Liskov substitution, Interface segregation, and Dependency inversion.",
      topic: "Software Engineering",
      difficulty: "MEDIUM",
    },
    {
      question: "What is the time complexity of binary search?",
      optionA: "O(n)",
      optionB: "O(n²)",
      optionC: "O(log n)",
      optionD: "O(n log n)",
      correctAnswer: "C",
      explanation: "Binary search halves the search space each iteration, resulting in O(log n) time complexity.",
      topic: "Data Structures & Algorithms",
      difficulty: "EASY",
    },
    {
      question: "Which HTTP method is idempotent and used to completely replace a resource?",
      optionA: "POST",
      optionB: "PATCH",
      optionC: "PUT",
      optionD: "DELETE",
      correctAnswer: "C",
      explanation: "PUT is idempotent and replaces the entire resource. POST creates new resources and is not idempotent.",
      topic: "Web Development",
      difficulty: "MEDIUM",
    },
    {
      question: "What is a deadlock in operating systems?",
      optionA: "A process that uses 100% CPU",
      optionB: "A situation where two or more processes wait indefinitely for resources held by each other",
      optionC: "A memory leak causing system slowdown",
      optionD: "A network timeout condition",
      correctAnswer: "B",
      explanation: "Deadlock occurs when processes form a circular wait — each holds a resource the next one needs.",
      topic: "Operating Systems",
      difficulty: "MEDIUM",
    },
    {
      question: "Which data structure uses LIFO (Last In, First Out) principle?",
      optionA: "Queue",
      optionB: "Heap",
      optionC: "Stack",
      optionD: "Linked List",
      correctAnswer: "C",
      explanation: "A Stack follows LIFO — the last element inserted is the first one removed. Queues use FIFO.",
      topic: "Data Structures",
      difficulty: "EASY",
    },
    {
      question: "What is the purpose of normalization in databases?",
      optionA: "To speed up read queries",
      optionB: "To reduce data redundancy and improve data integrity",
      optionC: "To encrypt sensitive data",
      optionD: "To replicate data across servers",
      correctAnswer: "B",
      explanation: "Normalization organizes data to reduce redundancy and dependency, ensuring data integrity.",
      topic: "Databases",
      difficulty: "MEDIUM",
    },
    {
      question: "What does REST stand for?",
      optionA: "Remote Execution Standard Technology",
      optionB: "Representational State Transfer",
      optionC: "Responsive Service Template",
      optionD: "Resource Exchange and State Technology",
      correctAnswer: "B",
      explanation: "REST (Representational State Transfer) is an architectural style for distributed hypermedia systems.",
      topic: "Web Development",
      difficulty: "EASY",
    },
    {
      question: "Which sorting algorithm has the best average-case time complexity?",
      optionA: "Bubble Sort",
      optionB: "Insertion Sort",
      optionC: "Quick Sort",
      optionD: "Selection Sort",
      correctAnswer: "C",
      explanation: "Quick Sort has an average-case complexity of O(n log n), making it the fastest among common algorithms.",
      topic: "Algorithms",
      difficulty: "MEDIUM",
    },
    {
      question: "What is encapsulation in OOP?",
      optionA: "The ability of a class to inherit from multiple parent classes",
      optionB: "Bundling data and methods that operate on that data within a single unit",
      optionC: "Defining multiple methods with the same name but different parameters",
      optionD: "Creating a template for objects",
      correctAnswer: "B",
      explanation: "Encapsulation bundles data (attributes) and behaviors (methods) together, hiding internal state.",
      topic: "Object-Oriented Programming",
      difficulty: "EASY",
    },
    {
      question: "What is a primary use of Git branching?",
      optionA: "To compress code files",
      optionB: "To work on features or fixes in isolation without affecting the main codebase",
      optionC: "To deploy code to production",
      optionD: "To manage database migrations",
      correctAnswer: "B",
      explanation: "Branches allow parallel development — teams can work on features independently before merging.",
      topic: "Version Control",
      difficulty: "EASY",
    },
    {
      question: "Which cloud computing model provides virtualized computing resources over the internet?",
      optionA: "SaaS",
      optionB: "PaaS",
      optionC: "IaaS",
      optionD: "FaaS",
      correctAnswer: "C",
      explanation: "IaaS (Infrastructure as a Service) provides virtualized computing resources like VMs, storage, and networking.",
      topic: "Cloud Computing",
      difficulty: "MEDIUM",
    },
    {
      question: "What is a race condition?",
      optionA: "A performance benchmark test",
      optionB: "When program behavior depends on the sequence or timing of uncontrollable events",
      optionC: "A competition between threads to finish first",
      optionD: "A memory overflow error",
      correctAnswer: "B",
      explanation: "A race condition occurs when two or more threads access shared data concurrently and the result depends on timing.",
      topic: "Concurrency",
      difficulty: "HARD",
    },
  ],

  "Data Analyst": [
    {
      question: "What SQL clause is used to filter groups in an aggregation?",
      optionA: "WHERE",
      optionB: "HAVING",
      optionC: "GROUP BY",
      optionD: "ORDER BY",
      correctAnswer: "B",
      explanation: "HAVING filters groups after GROUP BY aggregation. WHERE filters individual rows before grouping.",
      topic: "SQL",
      difficulty: "MEDIUM",
    },
    {
      question: "What is the median of the dataset: [3, 7, 2, 9, 5]?",
      optionA: "5",
      optionB: "7",
      optionC: "3",
      optionD: "9",
      correctAnswer: "A",
      explanation: "Sorted: [2, 3, 5, 7, 9]. The middle value (3rd of 5) is 5.",
      topic: "Statistics",
      difficulty: "EASY",
    },
    {
      question: "Which Python library is commonly used for data manipulation and analysis?",
      optionA: "NumPy",
      optionB: "Pandas",
      optionC: "Matplotlib",
      optionD: "Scikit-learn",
      correctAnswer: "B",
      explanation: "Pandas provides DataFrames for tabular data manipulation. NumPy handles numerical arrays, Matplotlib for visualization.",
      topic: "Python",
      difficulty: "EASY",
    },
    {
      question: "What is a JOIN in SQL?",
      optionA: "Adding two tables together vertically",
      optionB: "Combining rows from two or more tables based on a related column",
      optionC: "Creating a backup of a table",
      optionD: "Merging column names",
      correctAnswer: "B",
      explanation: "SQL JOIN combines rows from multiple tables based on a matching condition (usually a foreign key).",
      topic: "SQL",
      difficulty: "EASY",
    },
    {
      question: "What does standard deviation measure?",
      optionA: "The average value of a dataset",
      optionB: "The most frequent value in a dataset",
      optionC: "How spread out data points are from the mean",
      optionD: "The difference between max and min values",
      correctAnswer: "C",
      explanation: "Standard deviation quantifies the amount of variation or dispersion of a set of values from their mean.",
      topic: "Statistics",
      difficulty: "MEDIUM",
    },
    {
      question: "In Power BI, what is a DAX measure?",
      optionA: "A data transformation pipeline",
      optionB: "A formula that calculates results based on context from the report",
      optionC: "A visual chart type",
      optionD: "A database connection string",
      correctAnswer: "B",
      explanation: "DAX (Data Analysis Expressions) measures compute values dynamically based on filter context in a report.",
      topic: "Power BI",
      difficulty: "MEDIUM",
    },
    {
      question: "Which SQL function returns the number of rows?",
      optionA: "SUM()",
      optionB: "AVG()",
      optionC: "COUNT()",
      optionD: "MAX()",
      correctAnswer: "C",
      explanation: "COUNT() returns the number of rows matching a condition. COUNT(*) counts all rows.",
      topic: "SQL",
      difficulty: "EASY",
    },
    {
      question: "What is data normalization in analytics context?",
      optionA: "Removing null values from datasets",
      optionB: "Scaling data to a standard range, like 0 to 1",
      optionC: "Sorting data in ascending order",
      optionD: "Removing duplicate columns",
      correctAnswer: "B",
      explanation: "Normalization scales features to a uniform range to prevent high-magnitude features from dominating analysis.",
      topic: "Data Preprocessing",
      difficulty: "MEDIUM",
    },
    {
      question: "What is an outlier in a dataset?",
      optionA: "A data point that is incorrect",
      optionB: "A data point significantly different from other observations",
      optionC: "A missing value",
      optionD: "The average data point",
      correctAnswer: "B",
      explanation: "An outlier is a data point that lies far from most other data points and may indicate errors or rare events.",
      topic: "Statistics",
      difficulty: "EASY",
    },
    {
      question: "Which chart type is best for showing trends over time?",
      optionA: "Pie chart",
      optionB: "Bar chart",
      optionC: "Line chart",
      optionD: "Scatter plot",
      correctAnswer: "C",
      explanation: "Line charts are ideal for displaying continuous data trends over time with clear visual progression.",
      topic: "Data Visualization",
      difficulty: "EASY",
    },
    {
      question: "What is ETL in data engineering?",
      optionA: "Extract, Transform, Load",
      optionB: "Edit, Transfer, Link",
      optionC: "Encode, Translate, Launch",
      optionD: "Execute, Test, Log",
      correctAnswer: "A",
      explanation: "ETL (Extract, Transform, Load) is the process of extracting data from sources, transforming it, and loading it into a destination.",
      topic: "Data Engineering",
      difficulty: "MEDIUM",
    },
    {
      question: "What does correlation coefficient of -1 indicate?",
      optionA: "No correlation",
      optionB: "Perfect positive correlation",
      optionC: "Perfect negative correlation",
      optionD: "Weak negative correlation",
      correctAnswer: "C",
      explanation: "A correlation coefficient of -1 means a perfect inverse relationship — as one variable increases, the other decreases proportionally.",
      topic: "Statistics",
      difficulty: "MEDIUM",
    },
  ],

  "Frontend Developer": [
    {
      question: "What does the CSS 'z-index' property control?",
      optionA: "The zoom level of an element",
      optionB: "The stacking order of positioned elements",
      optionC: "The opacity of an element",
      optionD: "The border thickness",
      correctAnswer: "B",
      explanation: "z-index determines the stacking order of overlapping positioned elements. Higher values appear on top.",
      topic: "CSS",
      difficulty: "EASY",
    },
    {
      question: "In React, what is the purpose of 'useEffect'?",
      optionA: "To define component state",
      optionB: "To handle side effects like API calls and subscriptions",
      optionC: "To render JSX conditionally",
      optionD: "To create context providers",
      correctAnswer: "B",
      explanation: "useEffect runs side effects after render — such as data fetching, DOM manipulation, or event subscriptions.",
      topic: "React",
      difficulty: "MEDIUM",
    },
    {
      question: "What is the difference between 'display: none' and 'visibility: hidden'?",
      optionA: "They are identical in behavior",
      optionB: "display:none removes the element from layout; visibility:hidden hides it but retains space",
      optionC: "visibility:hidden removes the element; display:none hides it",
      optionD: "display:none applies only to block elements",
      correctAnswer: "B",
      explanation: "display:none removes the element from the flow entirely. visibility:hidden hides it but preserves its layout space.",
      topic: "CSS",
      difficulty: "MEDIUM",
    },
    {
      question: "What is event bubbling in JavaScript?",
      optionA: "Creating new events from existing ones",
      optionB: "An event propagating from a child element up to parent elements",
      optionC: "Preventing an event from firing",
      optionD: "Attaching events to dynamically created elements",
      correctAnswer: "B",
      explanation: "Event bubbling means an event triggered on a child element also triggers on all ancestor elements.",
      topic: "JavaScript",
      difficulty: "MEDIUM",
    },
    {
      question: "What does 'semantic HTML' mean?",
      optionA: "HTML with no CSS",
      optionB: "Using HTML elements that convey meaning about their content",
      optionC: "Minified HTML for performance",
      optionD: "HTML validated by W3C",
      correctAnswer: "B",
      explanation: "Semantic HTML uses meaningful tags like <article>, <nav>, <section> to describe content structure for browsers and screen readers.",
      topic: "HTML",
      difficulty: "EASY",
    },
    {
      question: "What is the Virtual DOM in React?",
      optionA: "A DOM tree stored in the database",
      optionB: "A lightweight JavaScript representation of the real DOM",
      optionC: "A DOM that only renders on server side",
      optionD: "An API for manipulating HTML directly",
      correctAnswer: "B",
      explanation: "React's Virtual DOM is an in-memory representation that React uses to diff changes before updating the real DOM efficiently.",
      topic: "React",
      difficulty: "MEDIUM",
    },
    {
      question: "What does CSS Flexbox's 'justify-content: space-between' do?",
      optionA: "Centers items vertically",
      optionB: "Places items at the start",
      optionC: "Distributes items with equal space between them",
      optionD: "Wraps items to the next line",
      correctAnswer: "C",
      explanation: "space-between distributes flex items evenly with no space before the first or after the last item.",
      topic: "CSS",
      difficulty: "EASY",
    },
    {
      question: "Which hook is used to store and update state in a functional React component?",
      optionA: "useContext",
      optionB: "useRef",
      optionC: "useState",
      optionD: "useMemo",
      correctAnswer: "C",
      explanation: "useState returns a stateful value and a setter function. Calling the setter re-renders the component with the new value.",
      topic: "React",
      difficulty: "EASY",
    },
    {
      question: "What is lazy loading in web performance?",
      optionA: "Loading all resources at once during page load",
      optionB: "Deferring loading of non-critical resources until they are needed",
      optionC: "Caching resources in the browser",
      optionD: "Compressing images before upload",
      correctAnswer: "B",
      explanation: "Lazy loading defers loading of images and components until they enter the viewport, improving initial page load time.",
      topic: "Web Performance",
      difficulty: "MEDIUM",
    },
    {
      question: "What is CORS?",
      optionA: "A CSS framework for responsive layouts",
      optionB: "A browser security mechanism controlling cross-origin HTTP requests",
      optionC: "A JavaScript module bundler",
      optionD: "A caching policy for static assets",
      correctAnswer: "B",
      explanation: "CORS (Cross-Origin Resource Sharing) controls which origins can access resources via browser HTTP requests.",
      topic: "Web Security",
      difficulty: "MEDIUM",
    },
    {
      question: "What does the 'async/await' syntax do in JavaScript?",
      optionA: "Runs code in parallel threads",
      optionB: "Makes asynchronous code look and behave like synchronous code",
      optionC: "Prevents callbacks from executing",
      optionD: "Compiles JavaScript to machine code",
      correctAnswer: "B",
      explanation: "async/await is syntactic sugar over Promises, making asynchronous code easier to read and write.",
      topic: "JavaScript",
      difficulty: "MEDIUM",
    },
    {
      question: "What is the purpose of 'key' prop in React lists?",
      optionA: "To style list items",
      optionB: "To help React identify which items have changed, been added, or removed",
      optionC: "To sort list items",
      optionD: "To prevent re-rendering of all items",
      correctAnswer: "B",
      explanation: "Keys help React reconcile the Virtual DOM efficiently by uniquely identifying list elements.",
      topic: "React",
      difficulty: "EASY",
    },
  ],

  "Digital Marketing Specialist": [
    {
      question: "What does SEO stand for?",
      optionA: "Social Engagement Optimization",
      optionB: "Search Engine Optimization",
      optionC: "Site Experience Orchestration",
      optionD: "Structured Email Outreach",
      correctAnswer: "B",
      explanation: "SEO (Search Engine Optimization) improves a website's visibility in organic search engine results.",
      topic: "SEO",
      difficulty: "EASY",
    },
    {
      question: "What is a CTR in digital marketing?",
      optionA: "Customer Tracking Report",
      optionB: "Click-Through Rate",
      optionC: "Content Transfer Rate",
      optionD: "Cost per Transaction Ratio",
      correctAnswer: "B",
      explanation: "CTR (Click-Through Rate) = (Clicks / Impressions) × 100. It measures ad or link effectiveness.",
      topic: "Analytics",
      difficulty: "EASY",
    },
    {
      question: "What is A/B testing in digital marketing?",
      optionA: "Testing two different websites against each other",
      optionB: "Comparing two versions of a webpage or ad to determine which performs better",
      optionC: "Testing website speed on different browsers",
      optionD: "Running ads on two different platforms",
      correctAnswer: "B",
      explanation: "A/B testing splits traffic between two variants to measure which drives better conversion or engagement.",
      topic: "Conversion Optimization",
      difficulty: "MEDIUM",
    },
    {
      question: "What does ROI stand for in marketing?",
      optionA: "Rate of Interest",
      optionB: "Return on Investment",
      optionC: "Reach of Impact",
      optionD: "Revenue on Impressions",
      correctAnswer: "B",
      explanation: "ROI = (Revenue - Cost) / Cost × 100. It measures the profitability of marketing spend.",
      topic: "Marketing Analytics",
      difficulty: "EASY",
    },
    {
      question: "Which metric best measures brand awareness?",
      optionA: "Conversion rate",
      optionB: "Customer lifetime value",
      optionC: "Impressions and reach",
      optionD: "Cost per acquisition",
      correctAnswer: "C",
      explanation: "Impressions (total views) and reach (unique viewers) are primary brand awareness metrics.",
      topic: "Brand Marketing",
      difficulty: "MEDIUM",
    },
    {
      question: "What is a landing page?",
      optionA: "The main homepage of a website",
      optionB: "A standalone web page created for a specific marketing campaign with one CTA",
      optionC: "A page that shows 404 errors",
      optionD: "A mobile-optimized page",
      correctAnswer: "B",
      explanation: "A landing page is designed for a single objective, directing visitors toward a specific action (signup, purchase, etc.).",
      topic: "Conversion Optimization",
      difficulty: "EASY",
    },
    {
      question: "What is email open rate?",
      optionA: "The percentage of emails delivered to inboxes",
      optionB: "The percentage of sent emails that were opened by recipients",
      optionC: "The number of emails that bounced",
      optionD: "The rate at which users unsubscribe",
      correctAnswer: "B",
      explanation: "Email open rate = (Opened / Delivered) × 100. A good open rate is typically 20-30%.",
      topic: "Email Marketing",
      difficulty: "EASY",
    },
    {
      question: "What is the main goal of content marketing?",
      optionA: "Immediate product sales",
      optionB: "Building long-term audience relationships by providing valuable content",
      optionC: "Increasing ad spend efficiency",
      optionD: "Reducing website bounce rate",
      correctAnswer: "B",
      explanation: "Content marketing builds trust and authority over time, attracting and retaining a defined audience.",
      topic: "Content Marketing",
      difficulty: "MEDIUM",
    },
    {
      question: "What does CPA stand for in paid advertising?",
      optionA: "Click Per Advertisement",
      optionB: "Cost Per Acquisition",
      optionC: "Content Performance Analytics",
      optionD: "Campaign Profit Average",
      correctAnswer: "B",
      explanation: "CPA (Cost Per Acquisition) measures how much it costs to acquire one customer through an ad campaign.",
      topic: "Paid Advertising",
      difficulty: "MEDIUM",
    },
    {
      question: "Which social media metric indicates post performance best?",
      optionA: "Number of followers",
      optionB: "Engagement rate (likes, comments, shares relative to reach)",
      optionC: "Profile visits",
      optionD: "Number of posts published",
      correctAnswer: "B",
      explanation: "Engagement rate shows how actively your audience interacts with content, indicating relevance and quality.",
      topic: "Social Media Marketing",
      difficulty: "MEDIUM",
    },
    {
      question: "What is remarketing?",
      optionA: "Marketing to new customers only",
      optionB: "Showing ads to people who previously visited your website or engaged with your brand",
      optionC: "Reposting old social media content",
      optionD: "Email campaigns to existing customers only",
      correctAnswer: "B",
      explanation: "Remarketing (retargeting) re-engages visitors who didn't convert, keeping your brand top-of-mind.",
      topic: "Paid Advertising",
      difficulty: "MEDIUM",
    },
    {
      question: "What is a unique selling proposition (USP)?",
      optionA: "The lowest price offered by a brand",
      optionB: "The single most important reason why customers should choose your product over competitors",
      optionC: "A special discount offer",
      optionD: "The tagline of an advertisement",
      correctAnswer: "B",
      explanation: "A USP differentiates your brand by communicating unique value that competitors cannot easily replicate.",
      topic: "Marketing Strategy",
      difficulty: "EASY",
    },
  ],
};

// General aptitude fallback (used for any role not in the bank)
export const APTITUDE_QUESTIONS: FallbackQuestion[] = [
  {
    question: "If a train travels 120 km in 2 hours, what is its speed?",
    optionA: "40 km/h",
    optionB: "60 km/h",
    optionC: "80 km/h",
    optionD: "100 km/h",
    correctAnswer: "B",
    explanation: "Speed = Distance / Time = 120 / 2 = 60 km/h.",
    topic: "Quantitative Aptitude",
    difficulty: "EASY",
  },
  {
    question: "What comes next in the series: 2, 4, 8, 16, ?",
    optionA: "24",
    optionB: "32",
    optionC: "28",
    optionD: "18",
    correctAnswer: "B",
    explanation: "Each term doubles the previous one: 16 × 2 = 32.",
    topic: "Logical Reasoning",
    difficulty: "EASY",
  },
  {
    question: "Find the odd one out: Apple, Mango, Carrot, Orange",
    optionA: "Apple",
    optionB: "Mango",
    optionC: "Carrot",
    optionD: "Orange",
    correctAnswer: "C",
    explanation: "Carrot is a vegetable; the rest are fruits.",
    topic: "Logical Reasoning",
    difficulty: "EASY",
  },
  {
    question: "A is 40% of B. B is what percent of A?",
    optionA: "150%",
    optionB: "200%",
    optionC: "250%",
    optionD: "300%",
    correctAnswer: "C",
    explanation: "If A = 0.4B, then B = A / 0.4 = 2.5A = 250% of A.",
    topic: "Quantitative Aptitude",
    difficulty: "MEDIUM",
  },
  {
    question: "Which word is closest in meaning to 'Eloquent'?",
    optionA: "Clumsy",
    optionB: "Articulate",
    optionC: "Secretive",
    optionD: "Reluctant",
    correctAnswer: "B",
    explanation: "Eloquent means fluent and persuasive in expression. Articulate means able to speak clearly and effectively.",
    topic: "Verbal Ability",
    difficulty: "MEDIUM",
  },
  {
    question: "If 5 workers complete a job in 8 days, how many days will 10 workers take?",
    optionA: "2",
    optionB: "4",
    optionC: "6",
    optionD: "8",
    correctAnswer: "B",
    explanation: "Total work = 5 × 8 = 40 worker-days. With 10 workers: 40 / 10 = 4 days.",
    topic: "Quantitative Aptitude",
    difficulty: "MEDIUM",
  },
  {
    question: "What is the next term: 1, 1, 2, 3, 5, 8, ?",
    optionA: "11",
    optionB: "13",
    optionC: "12",
    optionD: "10",
    correctAnswer: "B",
    explanation: "Fibonacci sequence: each term is the sum of the two preceding ones. 5+8=13.",
    topic: "Logical Reasoning",
    difficulty: "EASY",
  },
  {
    question: "Choose the grammatically correct sentence:",
    optionA: "She don't know the answer.",
    optionB: "She doesn't knows the answer.",
    optionC: "She doesn't know the answer.",
    optionD: "She do not knows the answer.",
    correctAnswer: "C",
    explanation: "With singular third-person subjects (she/he/it), use 'doesn't' + base verb form 'know'.",
    topic: "Verbal Ability",
    difficulty: "EASY",
  },
];

export function getQuestionsForRole(role: string, count: number = 10): FallbackQuestion[] {
  const roleQuestions = QUESTION_BANK[role] || [];
  const combined = [...roleQuestions, ...APTITUDE_QUESTIONS];
  
  // Shuffle and pick count questions
  const shuffled = combined.sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

export function shuffleOptions(question: FallbackQuestion): FallbackQuestion & { shuffledOptions: {key: string, text: string}[], newCorrect: string } {
  const options = [
    { key: "A", text: question.optionA },
    { key: "B", text: question.optionB },
    { key: "C", text: question.optionC },
    { key: "D", text: question.optionD },
  ];
  
  const correctText = options.find(o => o.key === question.correctAnswer)?.text || "";
  const shuffled = options.sort(() => Math.random() - 0.5);
  const newCorrect = shuffled.find(o => o.text === correctText)?.key || question.correctAnswer;
  
  return {
    ...question,
    optionA: shuffled[0].text,
    optionB: shuffled[1].text,
    optionC: shuffled[2].text,
    optionD: shuffled[3].text,
    correctAnswer: newCorrect as "A"|"B"|"C"|"D",
    shuffledOptions: shuffled,
    newCorrect,
  };
}
